[libraries]
# com.fasterxml.jackson.core:jackson-databind - Jackson Databind
# https://github.com/FasterXML/jackson-databind
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version = "2.21.1" }

# com.osmerion.omittable:omittable - Omittable
# https://github.com/Osmerion/Omittable
omittable = { module = "com.osmerion.omittable:omittable", version = "1.0.0" }

# org.jspecify - JSpecify
# https://github.com/jspecify/jspecify
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
